# Generated by Django 4.0.4 on 2022-05-26 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='measurementDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
